# configs.yaml
defaults:
  - env: local # default env (override via CLI: '+env=train_machine')
  - model: unet # chose model
  - optim: adam # chose optimizer
  - sched: cos_anneal # choose scheduler)
  - loss: composite/bce_iou # choose loss (single or composite)
  - _self_ # self-referencial (allows overrides)

batch_size: 6
epochs: 30
hydra:
  run:
    dir: .
