defaults:
  - env: local # chose the environment to define the dataset and checkpoint paths
  - model: unet # chose model
  - optim: adam # chose optimizer
  - sched: cos_anneal # choose scheduler
  - loss: composite/bce_iou # choose loss (single or composite)
  - _self_ # self-referencial (allows overrides)

batch_size: 6
device: "gpu"
epochs: 50
hydra:
  run:
    dir: .
