defaults:
  - env: local # chose the environment to define the dataset and checkpoint paths
  - model: unet # chose model
  - optim: adam # chose optimizer
  - sched: cos_anneal # choose scheduler
  - loss: composite/bce_iou # choose loss (single or composite)
  - logging: logging
  - training: training
  - _self_ # self-referencial (allows overrides)

hydra:
  run:
    dir: .
